### ISSUE TITLE
What is the difference between the diferent mods of "3d music"

### ISSUE THREAD

**Issue by Eragonfr** [mrDIMAS/rg3d-sound#3]
In the readme It's write that this library can support various format of "3d sound".  
```
Spatial sound sources.
HRTF support for excellent positioning and binaural effects.
```
What are the differences between these two mods of "3d sound" ?  
HRTF is related to the head, so how I can choose the best between the HRTF sphere models ?  
What is a Spatial sound ? How it work ?

And what is the best ? For what ?

**Comment by mrDIMAS** [comment]
Spatial sound is an audio source which can be positioned in 3d space, sound from such source will be processed using various methods.

In case of spatial sound there are quite few steps:
1) Apply panning based on listener's position and orientation. This basically creates effect of sound that placed somewhere in space.
2) Apply distance gain - this step defines how quite sound will be with increasing distance between listener and source.
Simple spatial sound sources are cheapest, it can work on slow CPU's without any problems. However perception quality is bad in this case: you can't really tell if sound is behind you or in front of you, above or below.

To solve this issue there is a special math construct - Head-Related Transfer Function (HRTF). I won't dive deep into math here (if you interested you can check References section in readme), all you need to know that it uses precomputed "head models" to significantly improve perception of sound. It replaces first step of "panning" computation, in case of HRTF sound you can definitely tell from which side sound came from. However there is a pitfall - each HRTF is individual, because there are no two persons with exactly the same ears, so to get ideal results you have to chose HRTF that suits you most. HRTF is much more heavier computation-wise, it uses a lot complex math  (Fourier transform, convolution, etc). 

What to choose and when? Use HRTF only if sound perception is crucial for you application, for example if you making horror game most likely that quality of sound will be on first place. If your application has lots of sounds on scene playing at the same time, it is better to use simple spatial sounds to reduce CPU load. To sum everything: use HRTF if you need high-quality sound.

**Comment by Eragonfr** [comment]
Thanks for your explications

If I'm making a First Person RPG, with lot of sounds, the best is spatial sound. But if I'm making an FPS the best is probably HRTF ?  
But, can I implement the two methods and let the user choose the best for him ?

**Comment by mrDIMAS** [comment]
Yes, you can switch renderers on context, check `hrtf` example: it does this 

```rust
let hrtf = HrtfSphere::new("examples/data/IRC_1002_C.bin").unwrap();
context.lock()
        .unwrap()
        .set_renderer(Renderer::HrtfRenderer(HrtfRenderer::new(hrtf)));
```

and you can switch it to default at any time

```rust
context.lock()
        .unwrap()
        .set_renderer(Renderer::Default);
```

Actually this could be an option in settings of game like "Sound quality" or something similar.

**Comment by Eragonfr** [comment]
Do I need to change a part of the code other than changing the render context ?  
Maybe certain things isn't supported by one but supported by the other ?

**Comment by mrDIMAS** [comment]
Just change renderer, it defines how sound is processed but does not affects API.

**Comment by Eragonfr** [comment]
Thank, can I'm closing the issue.  
You've answered all my questions
